List<Map<String, String>> tarotCards = [
  {"img": "assets/tarot/aceofcups.jpeg", "name": "Kupa Ası"},
  {"img": "assets/tarot/aceofpentacles.jpeg", "name": "Tılsım Ası"},
  {"img": "assets/tarot/aceofswords.jpeg", "name": "Kılıç Ası"},
  {"img": "assets/tarot/aceofwands.jpeg", "name": "Değnek Ası"},
  {"img": "assets/tarot/death.jpeg", "name": "Ölüm"},
  {"img": "assets/tarot/eightofcups.jpeg", "name": "Kupa Sekizlisi"},
  {"img": "assets/tarot/eightofpentacles.jpeg", "name": "Tılsım Sekizlisi"},
  {"img": "assets/tarot/eightofswords.jpeg", "name": "Kılıç Sekizlisi"},
  {"img": "assets/tarot/eightofwands.jpeg", "name": "Değnek Sekizlisi"},
  {"img": "assets/tarot/fiveofcups.jpeg", "name": "Kupa Beşlisi"},
  {"img": "assets/tarot/fiveofpentacles.jpeg", "name": "Tılsım Beşlisi"},
  {"img": "assets/tarot/fiveofswords.jpeg", "name": "Kılıç Beşlisi"},
  {"img": "assets/tarot/fiveofwands.jpeg", "name": "Değnek Beşlisi"},
  {"img": "assets/tarot/fourofcups.jpeg", "name": "Kupa Dörtlüsü"},
  {"img": "assets/tarot/fourofpentacles.jpeg", "name": "Tılsım Dörtlüsü"},
  {"img": "assets/tarot/fourofswords.jpeg", "name": "Kılıç Dörtlüsü"},
  {"img": "assets/tarot/fourofwands.jpeg", "name": "Değnek Dörtlüsü"},
  {"img": "assets/tarot/judgement.jpeg", "name": "Mahkeme"},
  {"img": "assets/tarot/justice.jpeg", "name": "Adalet"},
  {"img": "assets/tarot/kingofcups.jpeg", "name": "Kupa Kralı"},
  {"img": "assets/tarot/kingofpentacles.jpeg", "name": "Tılsım Kralı"},
  {"img": "assets/tarot/kingofswords.jpeg", "name": "Kılıç Kralı"},
  {"img": "assets/tarot/kingofwands.jpeg", "name": "Değnek Kralı"},
  {"img": "assets/tarot/knightofcups.jpeg", "name": "Kupa Şövalyesi"},
  {"img": "assets/tarot/knightofpentacles.jpeg", "name": "Tılsım Şövalyesi"},
  {"img": "assets/tarot/knightofswords.jpeg", "name": "Kılıç Şövalyesi"},
  {"img": "assets/tarot/knightofwands.jpeg", "name": "Değnek Şövalyesi"},
  {"img": "assets/tarot/nineofcups.jpeg", "name": "Kupa Dokuzlusu"},
  {"img": "assets/tarot/nineofpentacles.jpeg", "name": "Tılsım Dokuzlusu"},
  {"img": "assets/tarot/nineofswords.jpeg", "name": "Kılıç Dokuzlusu"},
  {"img": "assets/tarot/nineofwands.jpeg", "name": "Değnek Dokuzlusu"},
  {"img": "assets/tarot/pageofcups.jpeg", "name": "Kupa Sayfası"},
  {"img": "assets/tarot/pageofpentacles.jpeg", "name": "Tılsım Sayfası"},
  {"img": "assets/tarot/pageofswords.jpeg", "name": "Kılıç Sayfası"},
  {"img": "assets/tarot/pageofwands.jpeg", "name": "Değnek Sayfası"},
  {"img": "assets/tarot/queenofcups.jpeg", "name": "Kupa Kraliçesi"},
  {"img": "assets/tarot/queenofpentacles.jpeg", "name": "Tılsım Kraliçesi"},
  {"img": "assets/tarot/queenofswords.jpeg", "name": "Kılıç Kraliçesi"},
  {"img": "assets/tarot/queenofwands.jpeg", "name": "Değnek Kraliçesi"},
  {"img": "assets/tarot/sevenofcups.jpeg", "name": "Kupa Yedilisi"},
  {"img": "assets/tarot/sevenofpentacles.jpeg", "name": "Tılsım Yedilisi"},
  {"img": "assets/tarot/sevenofswords.jpeg", "name": "Kılıç Yedilisi"},
  {"img": "assets/tarot/sevenofwands.jpeg", "name": "Değnek Yedilisi"},
  {"img": "assets/tarot/sixofcups.jpeg", "name": "Kupa Altılısı"},
  {"img": "assets/tarot/sixofpentacles.jpeg", "name": "Tılsım Altılısı"},
  {"img": "assets/tarot/sixofswords.jpeg", "name": "Kılıç Altılısı"},
  {"img": "assets/tarot/sixofwands.jpeg", "name": "Değnek Altılısı"},
  {"img": "assets/tarot/temperance.jpeg", "name": "Denge"},
  {"img": "assets/tarot/tenofcups.jpeg", "name": "Kupa Onlusu"},
  {"img": "assets/tarot/tenofpentacles.jpeg", "name": "Tılsım Onlusu"},
  {"img": "assets/tarot/tenofswords.jpeg", "name": "Kılıç Onlusu"},
  {"img": "assets/tarot/tenofwands.jpeg", "name": "Değnek Onlusu"},
  {"img": "assets/tarot/thechariot.jpeg", "name": "Savaş Arabası"},
  {"img": "assets/tarot/thedevil.jpeg", "name": "Şeytan"},
  {"img": "assets/tarot/theemperor.jpeg", "name": "İmparator"},
  {"img": "assets/tarot/theempress.jpeg", "name": "İmparatoriçe"},
  {"img": "assets/tarot/thefool.jpeg", "name": "Aptal"},
  {"img": "assets/tarot/thehangedman.jpeg", "name": "Asılan Adam"},
  {"img": "assets/tarot/thehermit.jpeg", "name": "Ermiş"},
  {"img": "assets/tarot/thehierophant.jpeg", "name": "Başrahip"},
  {"img": "assets/tarot/thehighpriestess.jpeg", "name": "Başrahibe"},
  {"img": "assets/tarot/thelovers.jpg", "name": "Aşıklar"},
  {"img": "assets/tarot/themagician.jpeg", "name": "Büyücü"},
  {"img": "assets/tarot/themoon.jpeg", "name": "Ay"},
  {"img": "assets/tarot/thestar.jpeg", "name": "Yıldız"},
  {"img": "assets/tarot/thestrength.jpeg", "name": "Güç"},
  {"img": "assets/tarot/thesun.jpeg", "name": "Güneş"},
  {"img": "assets/tarot/thetower.jpeg", "name": "Kule"},
  {"img": "assets/tarot/theworld.jpeg", "name": "Dünya"},
  {"img": "assets/tarot/threeofcups.jpeg", "name": "Kupa Üçlüsü"},
  {"img": "assets/tarot/threeofpentacles.jpeg", "name": "Tılsım Üçlüsü"},
  {"img": "assets/tarot/threeofswords.jpeg", "name": "Kılıç Üçlüsü"},
  {"img": "assets/tarot/threeofwands.jpeg", "name": "Değnek Üçlüsü"},
  {"img": "assets/tarot/twoofcups.jpeg", "name": "Kupa İkilisi"},
  {"img": "assets/tarot/twoofpentacles.jpeg", "name": "Tılsım İkilisi"},
  {"img": "assets/tarot/twoofswords.jpeg", "name": "Kılıç İkilisi"},
  {"img": "assets/tarot/twoofwands.jpeg", "name": "Değnek İkilisi"},
  {"img": "assets/tarot/wheeloffortune.jpeg", "name": "Kader Çarkı"},
];
